version: '2'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 8080:8080
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
